---
openapi: 3.0.1
info:
  title: Codica managing project system API V1
  version: v1
paths:
  "/api/v1/current_users":
    get:
      summary: "/api/v1/current_users"
      security:
      - jwt: []
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    jwt:
      type: apiKey
      name: Authorization
      in: header
